# Generated by Django 5.2.5 on 2025-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_expense_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='split',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='split',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
